# Server Configuration
server.port=8080
server.servlet.context-path=/

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://goelvaibhav57_db_user:Hz8AUnLMQioar4gl@cluster0.b1uwcf6.mongodb.net/
spring.data.mongodb.database=ecommProuctDB
spring.data.mongodb.auto-index-creation=true

# Application Name
spring.application.name=catalog-api
# Logging Configuration
logging.level.root=INFO
logging.level.org.springframework.data.mongodb=DEBUG

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

aws.region=us-east-1
aws.s3.bucketName=product-images-dev1