name: Docker build -> push -> deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build jar
        run: |
          chmod +x ./mvnw
          ./mvnw clean package -DskipTests

      - name: Verify jar exists
        run: |
          ls -la
          ls -la target

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build docker Image
        run: docker build -t catalog-api .

      - name: Tag Docker Image
        run: | 
          docker tag catalog-api:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/vg-naggp/catalog:latest

      - name: Push image to ECR
        run: | 
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/vg-naggp/catalog:latest

      - name: Update kubeconfig for EKS
        run: |
          aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Deploy to Kubernetes
        run: |
          # Apply manifests
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          
          # Restart deployment to ensure update
          kubectl rollout restart deployment catalog-api || true

      - name: Verify deployment
        run: |
          kubectl get pods
          kubectl get svc

                
